version: '3'

services:
  benchmarker:
    image: benchmarker
    build:
      context: ../
      dockerfile: Dockerfile

    volumes:
      - ..:/opt/benchmarker:cached
      - ../data:/opt/benchmarker/data:cached

    entrypoint: tail -f /dev/null

    cap_add:
      - NET_ADMIN
